[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "B49Bt2vVghKTjvr7DxwqZvbuPWgoTgQugVtWzufAr9EA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
testsvm = "anchor build && cargo test"

[hooks]
